fieldLayouts:
  43ae3ef8-0740-49e6-8725-287f67c27567:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: bce57552-4cce-4dbb-aa89-398015020fda
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a2007d0c-252f-4367-8e53-da567f836922
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f6e8e9a4-1227-4191-96bb-cabd19b3e192
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: assets
hasUrls: true
name: Assets
settings:
  path: '@assetBasePath'
sortOrder: 1
type: craft\volumes\Local
url: '@assetBaseUrl'
