fieldLayouts:
  43ae3ef8-0740-49e6-8725-287f67c27567:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Nom du fichier'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 5258bc33-a2cb-4dd3-9a79-6a8db921d40c # Description
            instructions: ''
            label: Légende
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a2007d0c-252f-4367-8e53-da567f836922 #  Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bce57552-4cce-4dbb-aa89-398015020fda # Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fs: images
handle: images
hasUrls: true
name: Images
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: '@assetBaseUrl/images'
