fieldLayouts:
  43ae3ef8-0740-49e6-8725-287f67c27567:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Nom du fichier'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ea538a81-f665-4f7e-ac92-25ce00563a9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5258bc33-a2cb-4dd3-9a79-6a8db921d40c # Description
            instructions: null
            label: Légende
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4bc38e2-a851-459f-8a08-e18e0c99c644
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2007d0c-252f-4367-8e53-da567f836922 #  Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc49bc6f-0765-471a-9867-40c74afa0a84
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 5e36e5a5-26a0-4a32-a197-73e088e17497
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 49706b01-642a-4c91-a524-2bf00e1153b7
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
