module.exports = {
  useFloating: jest.fn(() => ({
    x: 0,
    y: 0,
    strategy: 'absolute',
    refs: {
      floating: { current: null },
      reference: { current: null },
      setReference: jest.fn(),
      setFloating: jest.fn(),
    },
    update: jest.fn(),
    context: {},
  })),
  useInteractions: jest.fn(() => ({
    getReferenceProps: jest.fn(),
    getFloatingProps: jest.fn(),
  })),
  useHover: jest.fn(() => ({})),
  useFocus: jest.fn(() => ({})),
  useClick: jest.fn(() => ({})),
  useDismiss: jest.fn(() => ({})),
  useRole: jest.fn(() => ({})),
  FloatingPortal: ({ children }) => children,
  FloatingArrow: () => null,
  arrow: jest.fn(),
  offset: jest.fn(),
  flip: jest.fn(),
  shift: jest.fn(),
  size: jest.fn(),
  autoUpdate: jest.fn(),
};
