version: 2.1

parameters:
  web-image:
    type: string
    default: "intactiledesign/puppetplays-web:<< pipeline.git.revision >>"
  web-image-release:
    type: string
    default: "intactiledesign/puppetplays-web:latest"
  admin-image:
    type: string
    default: "intactiledesign/puppetplays-admin:<< pipeline.git.revision >>"
  admin-image-release:
    type: string
    default: "intactiledesign/puppetplays-admin:latest"

jobs:
  build_web:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run build
          command: yarn run build
  docker_web:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: 
          name: Publish web image to docker hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
            docker pull << pipeline.parameters.web-image >> || true
            docker build --pull -t << pipeline.parameters.web-image >> --cache-from << pipeline.parameters.web-image >> puppetplays-web
            docker push << pipeline.parameters.web-image >>
            docker pull << pipeline.parameters.web-image >>
            docker tag << pipeline.parameters.web-image >> << pipeline.parameters.web-image-release >>
            docker push << pipeline.parameters.web-image-release >>
  docker_admin:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Publish admin image to docker hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
            docker pull << pipeline.parameters.admin-image >> || true
            docker build --pull -t << pipeline.parameters.admin-image >> --cache-from << pipeline.parameters.admin-image >> puppetplays-admin
            docker push << pipeline.parameters.admin-image >>
            docker pull << pipeline.parameters.admin-image >>
            docker tag << pipeline.parameters.admin-image >> << pipeline.parameters.admin-image-release >>
            docker push << pipeline.parameters.admin-image-release >>
  deploy_staging:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Deploy to staging server"

orbs:
  node: circleci/node@4.1.0

workflows:
  build:
    jobs:
      - build_web
      - docker_web:
          requires:
              - build_web
      - docker_admin
      - hold:
          type: approval
          requires:
            - build_web
            - docker_web
            - docker_admin
      - deploy_staging:
          requires:
            - hold
  