changedFieldIndicator: null
field: 4b4d08ca-b6dc-474c-a42e-d262395e7c89 # Sidebar
fieldLayouts:
  05c63ea0-3457-494c-8410-f6cceb629e70:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e55193f5-c240-4e32-89a4-dc79ea9ba233 # Sidebar Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46ef9144-c5b1-47fd-83e7-a167031c1bae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a81cd36-7b78-45e7-b5ba-0d98a54e344d
        userCondition: null
fields:
  e55193f5-c240-4e32-89a4-dc79ea9ba233: # Sidebar Content
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sidebarContent
    instructions: null
    name: 'Sidebar Content'
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_sidebarcontent}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
