changedFieldIndicator: 1757900443
field: 02a3e612-3fca-49e3-8d6b-db1557d980d5 # Side bar
fieldLayouts:
  06fb7d73-7ff8-439a-b15a-898051dbc285:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c23261bf-eb82-4a9e-8e69-29ac0bd335eb # Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e571e1dc-6424-4690-ad09-687b4315a32b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3785afa8-09ee-4026-b4ef-eb6aa1e4d2d3
        userCondition: null
fields:
  c23261bf-eb82-4a9e-8e69-29ac0bd335eb: # Block
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: block
    instructions: null
    name: Block
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_block}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
