fieldLayouts:
  773517a1-c4db-4c6a-99dd-711a5f85dafc:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Contenu
        sortOrder: 1
handle: audiences
hasTitleField: true
name: Publics
section: 9cac54fd-67ff-4311-a127-785048ff9146
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
