fieldLayouts:
  dde1177f-2838-4270-a988-0bf638a22da1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Contenu
        sortOrder: 1
handle: characters
hasTitleField: true
name: Personnages
section: bfd49b21-b009-43f4-bb18-fcb1b08f5bd5
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
