fieldLayouts:
  0c280a90-eb4c-47bc-8e59-fff6cc6079fa:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 3eec2c18-4dce-4184-a668-02f225266314 # Lieux
            instructions: ''
            label: 'Principaux lieux d’activité'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contenu
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 8d9ba885-0f2b-4591-926e-73e3a6ecc23f # Image principale
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 07c0d544-d28a-449e-a643-936d89cb7a3a # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Medias
        sortOrder: 2
handle: companies
hasTitleField: true
name: Compagnies
section: 63ea829e-b0e4-4021-8ab5-1b0f095d3daf # Personnes
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
