fieldLayouts:
  be2b10c6-9aa3-4d97-8e0d-0226ebe776d9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 6e173e2f-1a52-45d7-bc3d-ccd4901e799b
            instructions: ''
            label: 'Type d''institution'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3eec2c18-4dce-4184-a668-02f225266314
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contenu
        sortOrder: 1
handle: conservationInstitutions
hasTitleField: true
name: 'Institutions de conservation'
section: 492cc09a-052e-40d6-a33b-7ca74a831805
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
