fieldLayouts:
  011bcc92-0eaf-422c-9702-f36b5e0048f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b25a676f-c420-4e38-962f-3c0e750182d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 57929aa1-be57-43a8-9388-00000ad5e135 # Scientific Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f95265a-d56f-40fa-bfd8-2b7880ae476a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2342f554-5ab9-4053-befc-339cba3b6020 # Belongs to conference?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4cfabbe-a127-408a-9bd1-907a70d24d23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 2342f554-5ab9-4053-befc-339cba3b6020 # Belongs to conference?
                  uid: 2ce2440b-88db-4ab4-b3ce-10dac82cabda
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 4d0852b4-fe09-4414-8c8b-46ac23b63ff8 # Conference Group
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 951b6d4f-8e50-4202-9fcd-22e7381b8182
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: b4203563-5f48-443d-8744-0f9aa06422b6
            userCondition: null
          -
            elementCondition: null
            fieldUid: 2dd7c17a-3ef4-4aaf-a784-62648f6632fd # Auteur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f70d90e4-ee47-478b-96f2-7ddbfb80b1bb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 69e0955a-5deb-490f-8b73-6e852e245f4c # Author and ORCID identifier
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13084771-29e2-429d-a272-635b7c8834b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 96e274be-acfe-4d13-a01e-13b327b04fd1 # Langue(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f49d3ace-9a23-40db-8f80-53f3fde70013
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: be4f8219-2e2d-4fe7-8a7c-ecdb106189fb # Peer review
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f172d662-5545-4959-82aa-5cb7c9873f9e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 93ef4b66-f901-4820-a676-5130b59adcb4 # License
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0619c6d7-0997-4c31-8fb6-08a2831641f2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Book
            type: craft\fieldlayoutelements\Heading
            uid: fd04db1b-278b-4be1-aa35-5ac08b747910
            userCondition: null
          -
            elementCondition: null
            fieldUid: e31e7ecb-d2c2-413b-a9aa-f6b7d45f5a89 # Book title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d550db84-7901-4ecc-a7df-5bc5d30c2113
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Edition
            type: craft\fieldlayoutelements\Heading
            uid: 50450e22-f3c8-4e88-ac3b-1a0397cce788
            userCondition: null
          -
            elementCondition: null
            fieldUid: 268ec30e-43a1-429e-8600-787a223ae0dc # Name of the editor / magazine  
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3d7dcd5-c13a-4f32-9c69-6edd5f63fe24
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b2e52632-2de4-4bfa-acc7-3108249c6790 # Issn
            instructions: null
            label: ISSN
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3ce8085-694a-4e8e-82f4-b42654f5051f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: df947f02-658c-48b9-b53d-868af0bfc3e3 # Place of Edition
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c683d141-3de2-4800-9f04-861167df9201
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 269fbeb7-8282-427c-b9ff-7d338ab1b8ef # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb3c5a9b-02a7-49a8-8304-63a00e5c220d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a258b7d-1518-4112-85df-287c1f8c889f # Volume
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c71e3bf-a90d-4015-bc16-4713c0290c15
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2d8643ae-5357-48a9-a90c-59e78c29508c # Nombre de pages
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f2e9692-87d5-4524-9434-c0150f50f5e4
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 6f559531-bd88-46af-8cb6-96e4e5658f3b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3802b7c5-d17c-4241-873e-872425f9ea93 # DOI
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adea6b7d-4e62-4364-ba8c-37862a167f52
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f0a2592d-502a-4a22-8068-251e5bc3daa4 # HAL CV Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd2cb6a3-3fb2-45aa-88fa-9d2d25f6c81a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c029b233-7520-4738-ac83-4c8902abac5a # Nakala Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 039cdf88-311a-489c-bd20-bdec1aea10e0
            userCondition: null
            warning: null
            width: 100
        name: Identifiers
        uid: 4131fe04-e0f5-45a0-920e-e82f6043d3dd
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: f462f4e5-af46-4dfe-939c-e747d81aa405 # Scientific Publications
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
