fieldLayouts:
  0014e08f-d7f1-4f44-9640-07f7e3917dbb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2a696956-3c89-40f6-89de-9d522b331c7e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04bf26e9-d404-4a4d-904c-ef7b4d1863dc # Authors
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8e0b802-6d0a-407d-98ff-309951247435
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f344887-ea88-4889-9302-fb31f09d2562 # Nom de la publication
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8a940d7-ff28-49cf-980f-2d2a4f36ed5d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 55099d79-979a-4b39-9c2b-a1500480e690 # Lien vers l'article
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46887107-908d-40d0-8684-624514774277
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bfe721bf-2b01-4d3a-a6c6-c3af028f5400 # Date de publication
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a40e933-df7a-4de7-9965-4309f69ab2c5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5ac49c38-8dde-46d9-9d25-0eaec14af84f # Date de consultation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81964d5a-5484-4d55-b3ba-4b7705ce22b1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e9f030e0-d5e7-485b-be1a-39496843ac8c # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98a6a686-5e32-4cf6-8623-d245bf35a9ae
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 087c3213-bdce-4e30-99f4-e10f2caf1d3a
        userCondition: null
handle: default
hasTitleField: true
name: 'Par défaut'
section: c536c595-f070-49db-989a-a78e00ec515a # Revues de Presse 
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
