fieldLayouts:
  c7f07126-586b-4195-a5db-30f084870e39:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aa851033-9c7f-4bd0-972f-06e5683cf63b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Transcription
            type: craft\fieldlayoutelements\Heading
            uid: 84284523-9eb8-484f-9e2f-1cc2da48071a
            userCondition: null
          -
            elementCondition: null
            fieldUid: cf856488-e716-4834-a558-395405d8eeee # Transcripteur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7659c4e3-8d3a-4e1b-9363-4ff9da922524
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 41896b43-8bdf-40cd-b579-6b1796d66147 # Compilateur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3729973-8a0a-456f-a491-0f052dd25af6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 93ef4b66-f901-4820-a676-5130b59adcb4 # License
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f66f319c-39bf-47d7-8e3f-a938d79e7255
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 866eba7d-61f5-4679-984e-9f753f02a4fa
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3802b7c5-d17c-4241-873e-872425f9ea93 # DOI
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ca8ba21-b066-4781-ba80-dca12623e65d
            userCondition: null
            warning: null
            width: 100
        name: Identifiers
        uid: ff159cbc-a332-4a83-bbc0-bf34a27c4408
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: c57211bc-35a6-44ec-922a-839e348b5e6a # Anthologie
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
