fieldLayouts:
  14fe4e50-b876-4f67-99a7-0c4f2ead859b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: Nom
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 157ddd75-0868-4e2b-ba35-028ae3c8ae42 # Pays
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 69ee7666-95f0-4e8f-bf8b-09d970d7b777 # Latitude
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 07a590cd-d68b-4af3-96b5-4b6f46cebe31 # Longitude
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Contenu
        sortOrder: 1
handle: places
hasTitleField: true
name: Lieux
section: 6591dcc5-c98b-41db-91e2-1b3dcd8eb31b # Lieux
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
