fieldLayouts:
  bfcf3ee7-1bd4-41be-97db-87364aae072d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 2dd7c17a-3ef4-4aaf-a784-62648f6632fd # Auteur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 269fbeb7-8282-427c-b9ff-7d338ab1b8ef # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Contenu
        sortOrder: 1
handle: relatedWorks
hasTitleField: true
name: 'Œuvres corrélées'
section: e2d5c38e-3607-4630-bddf-0875190aa133 # Œuvres corrélées
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
