fieldLayouts:
  bfcf3ee7-1bd4-41be-97db-87364aae072d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aff8811c-9c9e-4fa6-9807-55705201a133
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2dd7c17a-3ef4-4aaf-a784-62648f6632fd # Auteur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51d21826-f10b-4fe8-ae28-c1119686a205
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 269fbeb7-8282-427c-b9ff-7d338ab1b8ef # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ed40433-8e59-404a-a829-0c2f0a9fc433
            userCondition: null
            warning: null
            width: 50
        name: Contenu
        uid: d9bb5d19-5fb8-4d81-bbab-74682c158135
        userCondition: null
handle: relatedWorks
hasTitleField: true
name: 'Œuvres corrélées'
section: e2d5c38e-3607-4630-bddf-0875190aa133 # Œuvres corrélées
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
