fieldLayouts:
  db752ba6-d5b2-42ef-a701-b0449fa8e0d7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ea36bca5-e49b-4715-a833-7320d2eeb43d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 34a701b5-35b7-44d7-95a8-3e83b22b2899 # Full Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 471dbb33-3b46-4bb5-9e33-dd481a9d0258
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a6880810-a754-4a93-9fd2-5803e60ad519 # Role
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0a69b78-585f-47f5-95f9-7a901e40a18c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c069fd63-6ce9-424a-b5e8-6cec84e5b447 # ORCID Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1e947ce-3e5b-45c0-97c0-ce36b4d7a3b1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f0a2592d-502a-4a22-8068-251e5bc3daa4 # HAL CV Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caf4d465-a6e9-4caf-9bc7-376e04044237
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6cf4b690-6dd1-4003-a2e9-60f991b8ba0c # Start Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3bec035-1c4d-474c-9221-eb4f1028b646
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 492cebb9-6c2f-4df5-accf-b7af4cdcabc5 # End Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cefeb3b-4805-4c56-b74f-9cd6629a1b07
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e780c89d-1896-434f-b228-1af758a8ab24 # Biography
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7d9b873-0bad-4d8b-af87-dabd5574e559
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d64e0372-dae1-4fc6-8e60-9fba1d23cf2d # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6822015e-2777-4d33-a25e-65ba910855e7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: decf110f-9d8b-4a8c-81a6-0da3455f349d
        userCondition: null
handle: team
hasTitleField: true
name: Equipe
section: 0a553f7b-fdc0-4aad-aef0-ae1ed91d4df6 # Equipe
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
