fieldLayouts:
  db752ba6-d5b2-42ef-a701-b0449fa8e0d7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8a46e93c-3046-488e-8550-9255cc3fde8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 34a701b5-35b7-44d7-95a8-3e83b22b2899 # Full Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd87d012-b01f-4b50-a2c7-215190a0a1ee
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a6880810-a754-4a93-9fd2-5803e60ad519 # Role
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24aa99d2-9657-462f-9d48-da7080757a96
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c069fd63-6ce9-424a-b5e8-6cec84e5b447 # ORCID Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5086f72-4514-4234-9acb-81519f78717a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f0a2592d-502a-4a22-8068-251e5bc3daa4 # HAL CV Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2508e1f-2ca5-4eec-a6dc-1422c201afe4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6cf4b690-6dd1-4003-a2e9-60f991b8ba0c # Start Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c153b045-fe16-47c0-ac8a-7abc1ef60f84
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 492cebb9-6c2f-4df5-accf-b7af4cdcabc5 # End Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30c1464d-d700-46d8-ae80-9dfcd9b238f0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e780c89d-1896-434f-b228-1af758a8ab24 # Biography
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a01d135b-ba4d-42b9-871d-dd629a377176
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d64e0372-dae1-4fc6-8e60-9fba1d23cf2d # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd4bfb09-6833-4ae2-83e1-0369146dee81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81de301-cf42-40e7-88d2-fcce6f00cafc # Research Project
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16bd0370-3a52-4409-bdc1-d478874240eb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cbe457db-98d5-4d77-b5aa-5da45ef6ad9c
        userCondition: null
handle: team
hasTitleField: true
name: Equipe
section: 0a553f7b-fdc0-4aad-aef0-ae1ed91d4df6 # Equipe
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
