field: c23261bf-eb82-4a9e-8e69-29ac0bd335eb
fieldLayouts:
  9394e65a-3817-45ec-ba2f-93372987fbf1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc187519-b38b-40f1-970a-984ee4517a17 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f458bb63-1eba-4dad-b115-251f742a5aff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e79f6c9c-65b3-4cce-8c3d-c673a9659684 # Elements
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0b947e4-4ee4-4c7a-9d4c-dea59af82823
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4e36efa4-8d78-4a47-88ce-25f3e39ae3c8
        userCondition: null
fields:
  cc187519-b38b-40f1-970a-984ee4517a17: # Title
    columnSuffix: kxptyekm
    contentColumnType: text
    fieldGroup: null
    handle: contentTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  e79f6c9c-65b3-4cce-8c3d-c673a9659684: # Elements
    columnSuffix: gntfggkb
    contentColumnType: text
    fieldGroup: null
    handle: elements
    instructions: null
    name: Elements
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Link
                -
                  - handle
                  - link
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
handle: contentBlock
name: 'Content Block'
sortOrder: 1
