field: dd1a4870-abc3-4341-b390-1a30cd07a558 # Parties
fieldLayouts:
  09e722d3-452a-42a0-9d43-eac1eb16222a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 408142ac-f959-4def-8f9a-5862b0175509 # title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 247aaf9c-0298-458e-8e56-bf8465147329
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4daf95e-20af-4dac-b0b9-7f562c5c3bc9 # url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c30de27-5d27-46bd-9c5a-5f2afc12caff
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fa95153b-9e8c-4920-9338-df41d11bfe43 # date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f652987d-1b42-4154-ba25-04de6e50c798
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5e4b9413-6946-4790-adef-b347f30fe4fe # thumbnail
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7ff754e-a222-4744-9e90-73f30ec84d1d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cc9a42ae-61f9-46fa-8757-048f9c5031e9
        userCondition: null
fields:
  5e4b9413-6946-4790-adef-b347f30fe4fe: # thumbnail
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: thumbnailBlock
    instructions: null
    name: thumbnail
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ef2dfdac-243c-4f75-8385-ee787d2e7765' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ef2dfdac-243c-4f75-8385-ee787d2e7765' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  408142ac-f959-4def-8f9a-5862b0175509: # title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: titleBlock
    instructions: null
    name: title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  e4daf95e-20af-4dac-b0b9-7f562c5c3bc9: # url
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: urlBlock
    instructions: null
    name: url
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  fa95153b-9e8c-4920-9338-df41d11bfe43: # date
    columnSuffix: null
    contentColumnType: datetime
    fieldGroup: null
    handle: dateBlock
    instructions: null
    name: date
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: 30
      showDate: true
      showTime: false
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
handle: partsBlock
name: partsBlock
sortOrder: 1
