field: e55193f5-c240-4e32-89a4-dc79ea9ba233 # Sidebar Content
fieldLayouts:
  e263f9dc-8213-4226-8245-37410d5895e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cb7c0e4b-a596-4f1a-ba5f-319d10e1df1e # Side Bar Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69e775a5-ac46-4310-957c-41f1ee50eb00
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 50293fbc-0526-44ba-8495-34a4f1b9cf41 # Sidebar Elements
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82d42faf-0058-4ca0-98f0-6bb4e251fa0a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8dee2c76-691c-4d67-a72b-6df926053487
        userCondition: null
fields:
  50293fbc-0526-44ba-8495-34a4f1b9cf41: # Sidebar Elements
    columnSuffix: cvyayvly
    contentColumnType: text
    fieldGroup: null
    handle: sidebarElements
    instructions: null
    name: 'Sidebar Elements'
    searchable: false
    settings:
      addRowLabel: 'Ajouter une ligne'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Anchor
                -
                  - handle
                  - anchor
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  cb7c0e4b-a596-4f1a-ba5f-319d10e1df1e: # Side Bar Title
    columnSuffix: zkvufalq
    contentColumnType: text
    fieldGroup: null
    handle: sideBarTitle
    instructions: null
    name: 'Side Bar Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: sidebarElement
name: 'Sidebar Element'
sortOrder: 1
