field: a91b45bb-9cf2-4282-8145-7f8a006d801b # Traductions
fieldLayouts:
  aaf137d1-4374-42bf-8154-dca46bd1703f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 980b265a-4482-43da-940c-1d595933f6db # Langue
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faa51afd-da00-46db-bd0b-1fa53de7d129
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 80e9ab34-aa2b-44e3-9798-dadda7e7a772 # Références bibliographiques
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3b88fd9-89b5-4647-8e0c-f819d66945bd
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: ab730dc9-e76f-40c5-82c5-c679e1ebd9dd
        userCondition: null
fields:
  80e9ab34-aa2b-44e3-9798-dadda7e7a772: # Références bibliographiques
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: bibliographicRecord
    instructions: null
    name: 'Références bibliographiques'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  980b265a-4482-43da-940c-1d595933f6db: # Langue
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: translationLanguage
    instructions: null
    name: Langue
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: 'Sélectionner une langue'
      showSiteMenu: true
      sources:
        - 'section:ec7faa37-6b19-44d2-95ec-2b752648c37d' # Langues
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: translation
name: Traduction
sortOrder: 1
