version: "3.3"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ${PUPPETPLAYS_HOST_DIR}/database/postgres:/var/lib/postgresql/data
    restart: always

  puppetplays-admin:
    container_name: puppetplays-admin
    image: intactiledesign/puppetplays-admin:${PUPPETPLAYS_VERSION}
    environment:
      - DB_DRIVER=pgsql
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_USER=$POSTGRES_DB
      - DB_DATABASE=$POSTGRES_DB
      - DB_SERVER=postgres
      - DB_PORT=5432
      - DB_SCHEMA=public
      - SECURITY_KEY
      - APP_ID=puppetplays
      - ENVIRONMENT
    ports:
      - "11000:8080"
    links:
      - "postgres"
    volumes:
      - ${PUPPETPLAYS_HOST_DIR}/logs:/app/storage/logs
    restart: always

  puppetplays-web:
    container_name: puppetplays-web
    image: intactiledesign/puppetplays-web:${PUPPETPLAYS_VERSION}
    ports:
      - "7000:3000"
    links:
      - "puppetplays-admin"
    restart: always
