version: "3.3"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ${PUPPETPLAYS_HOST_DIR}/database/postgres:/var/lib/postgresql/data
    restart: always

  puppetplays-admin:
    container_name: puppetplays-admin
    image: puppetplays/puppetplays-admin:${PUPPETPLAYS_VERSION}
    environment:
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=25M
      - PHP_UPLOAD_MAX_FILESIZE=25M
      - DB_DRIVER=pgsql
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_USER=$POSTGRES_DB
      - DB_DATABASE=$POSTGRES_DB
      - DB_SERVER=postgres
      - DB_PORT=5432
      - DB_SCHEMA=public
      - SECURITY_KEY
      - PLUGIN_WORKFLOW_KEY
      - APP_ID=puppetplays
      - ENVIRONMENT
      - SITE_URL
      - CP_URL
      - COOKIE_DOMAIN
      - EMAIL_HOSTNAME
      - EMAIL_PORT
      - EMAIL_SENDER
    ports:
      - "11000:8080"
    depends_on:
      - "postgres"
    volumes:
      - ${PUPPETPLAYS_HOST_DIR}/logs:/app/storage/logs
      - ${PUPPETPLAYS_HOST_DIR}/static:/app/web/static
    restart: always

  puppetplays-web:
    container_name: puppetplays-web
    image: puppetplays/puppetplays-web:${PUPPETPLAYS_VERSION}
    environment:
      - NEXT_PUBLIC_API_URL
    ports:
      - "7000:3000"
    depends_on:
      - "puppetplays-admin"
    restart: always
