columnSuffix: null
contentColumnType: text
fieldGroup: b3d3b5fa-565c-459c-b370-cc1dceca0750 # Persons
handle: biographicalNote
instructions: null
name: 'Notice biographique'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Simple.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
