contentColumnType: string
fieldGroup: ffcbd130-d01a-46e8-be41-572fa13bf2fb
handle: character
instructions: ''
name: Personnage
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Sélectionner un personnage'
  showSiteMenu: false
  source: null
  sources:
    - 'section:bfd49b21-b009-43f4-bb18-fcb1b08f5bd5'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
