contentColumnType: string
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099
handle: characters
instructions: ''
name: 'Personnages du texte'
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Sélectionner un ou plusieurs personnages du texte'
  showSiteMenu: true
  source: null
  sources:
    - 'section:53b06a2d-abbf-4ee4-b770-ca48f26e094e'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
