contentColumnType: datetime
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099
handle: compositionMaxDate
instructions: ''
name: 'Date d’écriture (max)'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: modules\sitemodule\fields\SimpleDate
