columnSuffix: null
contentColumnType: text
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099 # Works
handle: compositionDisplayDate
instructions: ''
name: 'Date d’écriture (pour l’affichage)'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
