columnSuffix: null
contentColumnType: integer(10)
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099 # Works
handle: compositionMinDate
instructions: null
name: 'Date d’écriture (min)'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 1000
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: 4
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
