columnSuffix: immovwxz
contentColumnType: datetime
fieldGroup: f1c3d1d7-7d32-4cd8-a468-27b4ad21d5db # Newsletters
handle: consultationDate
instructions: 'Date de consultation (pour les articles en ligne uniquement)'
name: 'Date de consultation'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
