columnSuffix: null
contentColumnType: text
fieldGroup: b3feeaa7-8778-465a-9010-dc86232c1fbb # Assets
handle: copyright
instructions: null
name: ' Copyright'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: '© …'
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
