columnSuffix: null
contentColumnType: text
fieldGroup: ffcbd130-d01a-46e8-be41-572fa13bf2fb # Commons
handle: date
instructions: null
name: Date
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
