contentColumnType: datetime
fieldGroup: b3d3b5fa-565c-459c-b370-cc1dceca0750
handle: deathDate
instructions: ''
name: 'Date de mort'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
