columnSuffix: null
contentColumnType: string
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099 # Works
handle: directors
instructions: ''
name: 'Metteur en scène'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Sélectionner un ou des metteur(s) en scène'
  showSiteMenu: true
  source: null
  sources:
    - 'section:63ea829e-b0e4-4021-8ab5-1b0f095d3daf' # Personnes
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
