contentColumnType: text
fieldGroup: ffcbd130-d01a-46e8-be41-572fa13bf2fb # Commons
handle: excerpt
instructions: ''
name: Extrait
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
