contentColumnType: datetime
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099
handle: firstPerformanceMinDate
instructions: ''
name: 'Date de la 1ère représentation minimum'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
