contentColumnType: string
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099
handle: firstPerformancePlace
instructions: ''
name: 'Lieu de la première représentation'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Sélectionner le lieu de la 1ère représentation'
  showSiteMenu: true
  source: null
  sources:
    - 'section:6591dcc5-c98b-41db-91e2-1b3dcd8eb31b'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
