columnSuffix: null
contentColumnType: text
fieldGroup: b3d3b5fa-565c-459c-b370-cc1dceca0750 # Persons
handle: firstName
instructions: null
name: Prénom
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
