columnSuffix: cpxukpir
contentColumnType: text
fieldGroup: 25d7ddec-23cf-442f-9870-0085d484be5f # Team
handle: fullName
instructions: ''
name: 'Full Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'e.g., "Dr Jean Boutan"'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
