columnSuffix: null
contentColumnType: string
fieldGroup: b3d3b5fa-565c-459c-b370-cc1dceca0750 # Persons
handle: gender
instructions: null
name: Genre
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - ''
        -
          - value
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Homme
        -
          - value
          - male
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Femme
        -
          - value
          - female
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
