contentColumnType: string
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099
handle: hypotexts
instructions: ''
name: Hypotexte(s)
searchable: false
settings:
  allowSelfRelations: false
  inputTemplate: sitemodule/_components/fields/HypotextEntries_input
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:e2d5c38e-3607-4630-bddf-0875190aa133'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: modules\sitemodule\fields\HypotextEntries
