columnSuffix: null
contentColumnType: text
fieldGroup: f6c0a973-aaab-4aee-bbdc-c5f7fe02069a # IDs
handle: idrefId
instructions: null
name: 'Identifiant IDREF'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
