contentColumnType: 'decimal(10,7)'
fieldGroup: 5dc50f30-9aba-4974-92fb-08b263ce5716 # Places
handle: longitude
instructions: ''
name: Longitude
searchable: false
settings:
  decimals: '7'
  defaultValue: null
  max: '180'
  min: '-180'
  prefix: ''
  previewCurrency: ''
  previewFormat: decimal
  size: '10'
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
