columnSuffix: null
contentColumnType: string
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099 # Works
handle: medias
instructions: ''
name: Medias
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: false
  allowedKinds:
    - audio
    - image
    - video
  defaultUploadLocationSource: 'volume:ef2dfdac-243c-4f75-8385-ee787d2e7765' # Images
  defaultUploadLocationSubpath: '{section.handle}'
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Sélectionner un ou plusieurs médias (images, vidéos, sons)'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:ef2dfdac-243c-4f75-8385-ee787d2e7765' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
