contentColumnType: string
fieldGroup: ba087b24-89e6-4a30-8ad7-d72a055d286c
handle: otherVersions
instructions: ''
name: 'Autre(s) version(s) du même nom'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Sélectionner un ou plusieurs personnage(s) du même nom'
  showSiteMenu: true
  source: null
  sources:
    - 'section:bfd49b21-b009-43f4-bb18-fcb1b08f5bd5'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
