columnSuffix: null
contentColumnType: text
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099 # Works
handle: otherTitles
instructions: null
name: 'Autre(s) titre(s)'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
