columnSuffix: rjadpkkh
contentColumnType: text
fieldGroup: e2264f91-0ef8-4237-9334-9b9061b59c0e # Partners
handle: partnerName
instructions: 'Official name of the partner organization'
name: 'Partner Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
