columnSuffix: null
contentColumnType: string
fieldGroup: fd15fc2d-a3c9-4686-891d-700dd34684ec # Communications
handle: parts
instructions: null
name: Parties
searchable: false
settings:
  contentTable: '{{%matrixcontent_parts}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
