contentColumnType: string
fieldGroup: ffcbd130-d01a-46e8-be41-572fa13bf2fb
handle: places
instructions: ''
name: Lieux
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Sélectionner un ou plusieurs lieux'
  showSiteMenu: true
  source: null
  sources:
    - 'section:6591dcc5-c98b-41db-91e2-1b3dcd8eb31b'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
