columnSuffix: null
contentColumnType: string
fieldGroup: ffcbd130-d01a-46e8-be41-572fa13bf2fb # Commons
handle: places
instructions: ''
name: Lieux
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Sélectionner un ou plusieurs lieu(x)'
  showSiteMenu: true
  source: null
  sources:
    - 'section:6591dcc5-c98b-41db-91e2-1b3dcd8eb31b' # Lieux
    - 'section:e205ebe8-5557-4b7c-a43f-9cf548e90c8d' # Pays
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
