columnSuffix: jhqkxjtf
contentColumnType: text
fieldGroup: 54aa53d7-846e-4221-bffd-56ad27828429 # Projets de Recherche
handle: projectTitle
instructions: 'Titre complet du projet de recherche postdoctoral'
name: 'Titre du Projet'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
