columnSuffix: null
contentColumnType: boolean
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099 # Works
handle: publicDomain
instructions: null
name: 'Domaine public'
searchable: false
settings:
  default: false
  offLabel: Non
  onLabel: Oui
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
