columnSuffix: qfqjhddy
contentColumnType: text
fieldGroup: f1c3d1d7-7d32-4cd8-a468-27b4ad21d5db # Revues de presse
handle: publicationName
instructions: 'Nom de la publication (journal, magazine, site web)'
name: 'Nom de la publication'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
