contentColumnType: string
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099
handle: register
instructions: ''
name: Registre
searchable: true
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Sélectionner un registre'
  showSiteMenu: true
  source: null
  sources:
    - 'section:8e72b0db-f5f6-4385-9228-33dd62285d5c'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
