columnSuffix: jhenkjjf
contentColumnType: text
fieldGroup: 25d7ddec-23cf-442f-9870-0085d484be5f # Team
handle: role
instructions: null
name: Role
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'e.g., "Post-doctorate"'
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
