columnSuffix: uabnbcte
contentColumnType: text
fieldGroup: ffcbd130-d01a-46e8-be41-572fa13bf2fb # Commons
handle: sheetTable2
instructions: null
name: sheetTable
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'First Column'
            -
              - handle
              - firstColumn
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Second Column'
            -
              - handle
              - secondColumn
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Third Column'
            -
              - handle
              - thirdColumn
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: site
type: craft\fields\Table
