columnSuffix: null
contentColumnType: string
fieldGroup: e92fa83e-6e31-4d20-a993-c04e900f1bd9 # Technical Documentation
handle: sideBar
instructions: null
name: 'Side bar'
searchable: false
settings:
  errorMessage: 'Component class ''verbb\supertable\fields\SuperTableField'' belongs to an uninstalled plugin (Super Table).'
  expectedType: verbb\supertable\fields\SuperTableField
  settings:
    __assoc__:
      0:
        - blockTypeFields
        - 0
      1:
        - changedFieldIndicator
        - 173685933
      2:
        - columns
        -
          __assoc__:
            -
              - 3130a680-11f2-4c70-9253-11a4384a363c
              -
                __assoc__:
                  -
                    - width
                    - ''
      3:
        - contentTable
        - '{{%stc_sidebar}}'
      4:
        - fieldLayout
        - table
      8:
        - propagationMethod
        - all
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
