contentColumnType: text
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099
handle: subtitle
instructions: ''
name: Sous-titre
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
