columnSuffix: null
contentColumnType: string
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099 # Works
handle: textCharacters
instructions: null
name: 'Personnages du texte'
searchable: true
settings:
  contentTable: '{{%matrixcontent_textcharacters}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
