columnSuffix: null
contentColumnType: text
fieldGroup: ba087b24-89e6-4a30-8ad7-d72a055d286c # Characters
handle: textName
instructions: ''
name: 'Nom du personnage dans le texte'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
