contentColumnType: text
fieldGroup: ffcbd130-d01a-46e8-be41-572fa13bf2fb
handle: thesaurusDefinition
instructions: ''
name: 'Définition du thésaurus'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
