columnSuffix: null
contentColumnType: string
fieldGroup: ffcbd130-d01a-46e8-be41-572fa13bf2fb # Commons
handle: thumbnail
instructions: ''
name: Thumbnail
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:ef2dfdac-243c-4f75-8385-ee787d2e7765' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:ef2dfdac-243c-4f75-8385-ee787d2e7765' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:ef2dfdac-243c-4f75-8385-ee787d2e7765' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
