contentColumnType: text
fieldGroup: f6c0a973-aaab-4aee-bbdc-c5f7fe02069a
handle: viafId
instructions: ''
name: 'Identifiant VIAF'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
