tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: ea500c41-2beb-4ed4-a12c-afca214004c7 # Superviseur
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 635e18c0-691a-49fb-926c-2126bef46965
        userCondition: null
        warning: null
        width: 100
    name: Configuration
    uid: e0d9b6b0-3e13-41b3-872e-e6061a7cada5
    userCondition: null
