tabs:
  -
    elements:
      -
        fieldUid: ea500c41-2beb-4ed4-a12c-afca214004c7 # Superviseur
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: Configuration
    sortOrder: 1
