defaultPlacement: end
enableVersioning: true
handle: anthology
name: Anthology
propagationMethod: all
siteSettings:
  397a9f9f-ff18-42c4-98ff-dbb87c17b754: # Puppetplays FR
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'anthology/{slug}'
  59986aab-e6c1-4cdf-a062-8db833d2b327: # Puppetplays EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'anthology/{slug}'
type: channel
