enableVersioning: false
handle: dramaticDevices
name: 'Procédés dramatiques'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Page entrée primaire'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4cda444a-a132-4409-8e1e-5205e6a53896:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'techniques-dramaturgiques/{slug}'
  397a9f9f-ff18-42c4-98ff-dbb87c17b754:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'techniques-dramaturgiques/{slug}'
  59986aab-e6c1-4cdf-a062-8db833d2b327:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'dramaturgic-techniques/{slug}'
  bf194204-844c-4373-ad71-db3f6243b824:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'techniques-dramaturgiques/{slug}'
type: channel
