enableVersioning: false
handle: persons
name: Personnes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Page entrée primaire'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  397a9f9f-ff18-42c4-98ff-dbb87c17b754:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'personnes/{slug}'
  59986aab-e6c1-4cdf-a062-8db833d2b327:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'persons/{slug}'
type: channel
