enableVersioning: true
handle: works
name: Œuvres
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Page FR'
      -
        - urlFormat
        - '{alias(''@livePreviewUrl'')}/oeuvres/{sourceId}/slug'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'Page EN'
      -
        - urlFormat
        - '{alias(''@livePreviewUrl'')}/en/oeuvres/{sourceId}/slug'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'Page IT'
      -
        - urlFormat
        - '{alias(''@livePreviewUrl'')}/it/oeuvres/{sourceId}/slug'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'Page DE'
      -
        - urlFormat
        - '{alias(''@livePreviewUrl'')}/de/oeuvres/{sourceId}/slug'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  397a9f9f-ff18-42c4-98ff-dbb87c17b754:
    enabledByDefault: false
    hasUrls: true
    template: null
    uriFormat: 'oeuvres/{slug}'
  4cda444a-a132-4409-8e1e-5205e6a53896:
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
  59986aab-e6c1-4cdf-a062-8db833d2b327:
    enabledByDefault: false
    hasUrls: true
    template: null
    uriFormat: 'works/{slug}'
  bf194204-844c-4373-ad71-db3f6243b824:
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
type: channel
