<?php

namespace craft\contentmigrations;

interface Countries {

    // Constants .............................................................................................
    const COUNTRIES_FR = [
        'Albanie',
        'Andorre',
        'Arménie',
        'Autriche',
        'Azerbaïdjan',
        'Biélorussie',
        'Belgique',
        'Bosnie Herzégovine',
        'Bulgarie',
        'Croatie',
        'Chypre',
        'Tchéquie',
        'Danemark',
        'Estonie',
        'Finlande',
        'France',
        'Géorgie',
        'Allemagne',
        'Grèce',
        'Hongrie',
        'Islande',
        'Irlande',
        'Italie',
        'Kazakhstan',
        'Kosovo',
        'Lettonie',
        'Liechtenstein',
        'Lituanie',
        'Luxembourg',
        'Malte',
        'Moldavie',
        'Monaco',
        'Monténégro',
        'Pays-Bas',
        'Macédoine du Nord',
        'Norvège',
        'Pologne',
        'Le Portugal',
        'Roumanie',
        'Russie',
        'Saint Marin',
        'Serbie',
        'Slovaquie',
        'Slovénie',
        'Espagne',
        'Suède',
        'Suisse',
        'Dinde',
        'Ukraine',
        'Royaume-Uni',
        'Cité du Vatican'
    ];
    
    const COUNTRIES_EN = [
        'Albania',
        'Andorra',
        'Armenia',
        'Austria',
        'Azerbaijan',
        'Belarus',
        'Belgium',
        'Bosnia and Herzegovina',
        'Bulgaria',
        'Croatia',
        'Cyprus',
        'Czechia',
        'Denmark',
        'Estonia',
        'Finland',
        'France',
        'Georgia',
        'Germany',
        'Greece',
        'Hungary',
        'Iceland',
        'Ireland',
        'Italy',
        'Kazakhstan',
        'Kosovo',
        'Latvia',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Malta',
        'Moldova',
        'Monaco',
        'Montenegro',
        'Netherlands',
        'North Macedonia',
        'Norway',
        'Poland',
        'Portugal',
        'Romania',
        'Russia',
        'San Marino',
        'Serbia',
        'Slovakia',
        'Slovenia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Turkey',
        'Ukraine',
        'United Kingdom',
        'Vatican City'
    ];

    const COUNTRIES_IT = [
        'Albania',
        'Andorra',
        'Armenia',
        'Austria',
        'Azerbaigian',
        'Bielorussia',
        'Belgio',
        'Bosnia Erzegovina',
        'Bulgaria',
        'Croazia',
        'Cipro',
        'Cechia',
        'Danimarca',
        'Estonia',
        'Finlandia',
        'Francia',
        'Georgia',
        'Germania',
        'Grecia',
        'Ungheria',
        'Islanda',
        'Irlanda',
        'Italia',
        'Kazakistan',
        'Kosovo',
        'Lettonia',
        'Liechtenstein',
        'Lituania',
        'Lussemburgo',
        'Malta',
        'Moldova',
        'Monaco',
        'Montenegro',
        'Olanda',
        'Macedonia del Nord',
        'Norvegia',
        'Polonia',
        'Portogallo',
        'Romania',
        'Russia',
        'San Marino',
        'Serbia',
        'Slovacchia',
        'Slovenia',
        'Spagna',
        'Svezia',
        'Svizzera',
        'Tacchino',
        'Ucraina',
        'Regno Unito',
        'Città del Vaticano'
    ];

    const COUNTRIES_GE = [
        'Albanien',
        'Andorra',
        'Armenien',
        'Österreich',
        'Aserbaidschan',
        'Weißrussland',
        'Belgien',
        'Bosnien und Herzegowina',
        'Bulgarien',
        'Kroatien',
        'Zypern',
        'Tschechien',
        'Dänemark',
        'Estland',
        'Finnland',
        'Frankreich',
        'Georgia',
        'Deutschland',
        'Griechenland',
        'Ungarn',
        'Island',
        'Irland',
        'Italien',
        'Kasachstan',
        'Kosovo',
        'Lettland',
        'Liechtenstein',
        'Litauen',
        'Luxemburg',
        'Malta',
        'Moldawien',
        'Monaco',
        'Montenegro',
        'Niederlande',
        'Nordmakedonien',
        'Norwegen',
        'Polen',
        'Portugal',
        'Rumänien',
        'Russland',
        'San Marino',
        'Serbien',
        'Slowakei',
        'Slowenien',
        'Spanien',
        'Schweden',
        'Schweiz',
        'Truthahn',
        'Ukraine',
        'Vereinigtes Königreich',
        'Vatikanstadt'
    ];
}