dateModified: 1650441081
email:
  fromEmail: $EMAIL_SENDER
  fromName: Puppetplays
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: ''
    host: $EMAIL_HOSTNAME
    password: ''
    port: $EMAIL_PORT
    timeout: '10'
    useAuthentication: ''
    username: ''
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    0efb8d7c-638f-4652-b952-44092a5657f1: 'Nombre d’actes / de parties' # Nombre d’actes / de parties
    0f4c66c2-2100-45f0-88f3-0f6f4d473f63: 'Langue principale' # Langue principale
    1b752928-627a-4f0d-a6a9-41a22636ab41: Public # Public
    1bddc6ff-b8f1-4708-af28-108cd6e92099: Works # Works
    1c1041b2-7307-47b5-b3da-f7da389ed14b: 'Domaine public' # Domaine public
    2a3117bf-dd2f-46f2-802d-42fbd2e52e0a: Pseudonyme # Pseudonyme
    2cbf68ec-55ec-4aee-bf2d-b255cad39232: Langues # Langues
    2d8643ae-5357-48a9-a90c-59e78c29508c: 'Nombre de pages' # Nombre de pages
    2dd7c17a-3ef4-4aaf-a784-62648f6632fd: Auteur # Auteur
    2f8bb2d7-f182-4a78-afa8-46f228a557e6: Traduction # Traduction
    3b937625-42ca-4656-9a7b-c999af708c26: 'Date de la 1ère représentation (min)' # Date de la 1ère représentation (min)
    03d78236-fed0-4e43-b21c-f2cd1a49e83c: Personnage # Personnage
    3df1d9d7-f431-4e77-8af6-67a22c501379: 'Identifiant ARK' # Identifiant ARK
    3eec2c18-4dce-4184-a668-02f225266314: Lieux # Lieux
    3fea7d7b-8c14-4919-8016-7d214ca2314b: 'Thème principal' # Thème principal
    4cda444a-a132-4409-8e1e-5205e6a53896: 'Puppetplays IT' # Puppetplays IT
    4d1dd542-4f61-4ce4-a1c8-2f969ecd3da1: 'Nom dans le texte' # Nom dans le texte
    5c594932-2c3a-4678-9988-3ee891a6df21: 'Date de référence' # Date de référence
    5dc50f30-9aba-4974-92fb-08b263ce5716: Places # Places
    5e83af75-a401-46c6-918f-f56ab78ad797: 'Procédés théâtraux' # Procédés théâtraux
    6e173e2f-1a52-45d7-bc3d-ccd4901e799b: Type # Type
    6e506719-d279-4e2c-9e84-fbf315440712: 'Nom de famille' # Nom de famille
    07a590cd-d68b-4af3-96b5-4b6f46cebe31: Longitude # Longitude
    07c0d544-d28a-449e-a643-936d89cb7a3a: Images # Images
    07cc50ee-05e5-483d-8911-22552f44be92: 'Personnages du texte' # Personnages du texte
    8c8213c1-75f5-4c1c-bc23-96b213711e06: Formats # Formats
    8d9ba885-0f2b-4591-926e-73e3a6ecc23f: 'Image principale' # Image principale
    8e095ccd-7ed1-4c9b-99e1-b98480a0e9df: Compagnies # Compagnies
    8e72b0db-f5f6-4385-9228-33dd62285d5c: 'Registres littéraires' # Registres littéraires
    9cac54fd-67ff-4311-a127-785048ff9146: Publics # Publics
    09da97ae-fc6f-4555-ade3-73e42fd9bf6a: Œuvres # Œuvres
    9e670e52-0ab0-4dc1-a6e1-adc8efea5c13: 'Notice biographique' # Notice biographique
    18acc84f-5d36-4e13-8a6b-deff0a3d529b: 'Mots-clé des œuvres' # Mots-clé des œuvres
    22b828fc-b5e2-42a0-9050-446047f73230: Formats # Formats
    23c8664d-0988-47dc-96c4-e3887b436569: Prénom # Prénom
    24beaf42-46d7-469b-b31a-79442e5bd3bf: 'Date d’édition (max)' # Date d’édition (max)
    26b83bbf-b7b9-48cd-979e-d69b22bceaf1: Résumé # Résumé
    29f1cf63-9c38-484a-9026-94010557c5af: Œuvres # Œuvres
    33cd919f-b3f5-4276-be62-d114dbab9934: Personnages # Personnages
    040b562a-a40a-4667-84e7-0dc3ea1787ac: 'Édition moderne' # Édition moderne
    42a8e3c5-6dcf-483a-93e3-a0f462764cfc: Sous-titre # Sous-titre
    45df3231-3a21-4a0c-93ea-01b0f58c5582: 'Genre (indiqué par l’auteur)' # Genre (indiqué par l’auteur)
    51f537ef-8b54-4c2f-b68c-f19542600077: 'Lieu d’écriture' # Lieu d’écriture
    53b06a2d-abbf-4ee4-b770-ca48f26e094e: 'Nom du personnage dans le texte' # Nom du personnage dans le texte
    63ea829e-b0e4-4021-8ab5-1b0f095d3daf: Personnes # Personnes
    65cde714-d150-4ea5-9f9a-da868a716343: 'Nom du personnage pour l’indexation' # Nom du personnage pour l’indexation
    69ee7666-95f0-4e8f-bf8b-09d970d7b777: Latitude # Latitude
    72de1311-0c34-4fe9-b04c-813fbc8a7923: 'Oeuvres corrélées à indexer' # Oeuvres corrélées à indexer
    72f7b794-21cc-4ef3-869b-e425785555fb: 'Date de la 1ère représentation (max)' # Date de la 1ère représentation (max)
    80e9ab34-aa2b-44e3-9798-dadda7e7a772: 'Références bibliographiques' # Références bibliographiques
    084dbff2-63eb-420b-aac6-22102df927f9: Hypotexte(s) # Hypotexte(s)
    91e5559d-8541-4d49-90fa-8f06aefe00b7: 'Identifiant VIAF' # Identifiant VIAF
    92ef2670-a9bc-47e7-9d07-dfdbee32a0b2: Lieux # Lieux
    93a3496b-76b7-4696-8639-1c44294aeec0: 'Informations complémentaires sur la licence' # Informations complémentaires sur la licence
    96e274be-acfe-4d13-a01e-13b327b04fd1: Langue(s) # Langue(s)
    155d31de-d871-4f90-a86c-9d29b851c29d: Medias # Medias
    157ddd75-0868-4e2b-ba35-028ae3c8ae42: Pays # Pays
    209da50a-0d77-41a6-9d9c-8946eb198e71: 'Nom du personnage dans le texte' # Nom du personnage dans le texte
    269fbeb7-8282-427c-b9ff-7d338ab1b8ef: Date # Date
    397a9f9f-ff18-42c4-98ff-dbb87c17b754: 'Puppetplays FR' # Puppetplays FR
    412f63f1-746e-468d-8c05-6e0deedc2b05: 'Procédés théâtraux' # Procédés théâtraux
    461b2661-d7d4-4998-8e56-f8ed7dacfb2f: 'Titre traduit' # Titre traduit
    492cc09a-052e-40d6-a33b-7ca74a831805: 'Institutions de conservation' # Institutions de conservation
    980b265a-4482-43da-940c-1d595933f6db: Langue # Langue
    1817d1f9-6682-4c22-b338-19654ae0c45c: 'Techniques d’animation' # Techniques d’animation
    2955ed2b-b666-48a6-81c5-99e6d9de1253: 'Type d''image' # Type d'image
    3023cfcd-a11d-4ed7-b779-4b40493ac931: Édition # Édition
    3802b7c5-d17c-4241-873e-872425f9ea93: DOI # DOI
    5258bc33-a2cb-4dd3-9a79-6a8db921d40c: Description # Description
    6591dcc5-c98b-41db-91e2-1b3dcd8eb31b: Lieux # Lieux
    19568c88-e81b-48e1-bab2-ba7f106a823f: Registres # Registres
    28340a2e-58f9-44f0-92dd-eb54581b97a0: 'Date d’édition (min)' # Date d’édition (min)
    37720b4b-f4c6-42b4-8400-af5f71b3e072: Sounds # Sounds
    41896b43-8bdf-40cd-b579-6b1796d66147: Compilateur # Compilateur
    59986aab-e6c1-4cdf-a062-8db833d2b327: 'Puppetplays EN' # Puppetplays EN
    67544b27-a5f2-4753-acf4-8a396c6d000e: 'Personnages originaux' # Personnages originaux
    93343e67-8611-4266-b864-d311771afbc9: 'Technique d’animation' # Technique d’animation
    240995cf-5c01-4d81-8338-b19a74e20d1a: 'Identifiant ISNI' # Identifiant ISNI
    09401318-0a4b-4b56-a6c4-c57d3b151579: 'Exemplaire en ligne' # Exemplaire en ligne
    48645943-e026-4046-ae42-c8efbe3d0b1c: Videos # Videos
    48898581-e621-4ea2-bcf6-3c65ac54487f: 'Techniques d’animation' # Techniques d’animation
    66501227-1575-4af8-9ad7-8ddf21716146: 'Nom usuel' # Nom usuel
    a5c71adc-184b-49c4-8e1a-d251540bf2b1: Chercheurs # Chercheurs
    a36b8a5f-17c5-46c5-8d97-43a29656c564: 'Date de mort' # Date de mort
    a47eb338-13e7-427d-a6a9-9854d7ecf096: Format # Format
    a91b45bb-9cf2-4282-8145-7f8a006d801b: Traductions # Traductions
    a457d850-4cd2-457c-9827-969f730ec77c: 'Nom traduit' # Nom traduit
    a2007d0c-252f-4367-8e53-da567f836922: ' Copyright' #  Copyright
    a63454cc-f4ca-4c63-a17f-8772cff10def: 'Date d’écriture (pour l’affichage)' # Date d’écriture (pour l’affichage)
    a95459b0-9778-477e-ac36-580e1a77e951: puppetplays # puppetplays
    a5261331-a813-4df9-ab61-a125b7713179: Genre # Genre
    afb33e8b-94e9-457a-87c1-3b2a96e3c804: 'Metteur en scène' # Metteur en scène
    b3d3b5fa-565c-459c-b370-cc1dceca0750: Persons # Persons
    b3feeaa7-8778-465a-9010-dc86232c1fbb: Assets # Assets
    b37dab53-e816-48fb-aa32-daece0392d17: 'Lieu de conservation' # Lieu de conservation
    b203ce66-4f2e-4fab-a0be-e3b6d42f7e41: 'Public Schema' # Public Schema
    b242aefb-6f05-426e-9110-18ac25105c2e: 'Première représentation (informations complémentaires)' # Première représentation (informations complémentaires)
    b4287b8a-4f37-43f2-894b-428e99411a04: 'Date d’écriture (min)' # Date d’écriture (min)
    ba087b24-89e6-4a30-8ad7-d72a055d286c: Characters # Characters
    bce57552-4cce-4dbb-aa89-398015020fda: Alt # Alt
    bd5e6b34-8b0b-4a47-93f3-f9a23c0a39aa: Pays # Pays
    bf194204-844c-4373-ad71-db3f6243b824: 'Puppetplays DE' # Puppetplays DE
    bfac270e-899c-4fde-90e4-d4fbb11f05ea: Accueil # Accueil
    bfd49b21-b009-43f4-bb18-fcb1b08f5bd5: 'Nom du personnage pour l’indexation' # Nom du personnage pour l’indexation
    c2a06b9d-03a3-471c-8452-f62e2d17e60f: Surnom # Surnom
    c8c55cf1-a8a5-4356-b4eb-7984788d01b2: Contributeurs # Contributeurs
    c18b0f9d-717f-4ce0-a996-f482d7432dba: 'Date de naissance' # Date de naissance
    c39eea87-c2d5-4632-bcb0-f6e737f34e0f: Lieu # Lieu
    c117b558-d303-4933-b64d-1856bbe54d59: 'Date de la première représentation' # Date de la première représentation
    ccd48638-f531-4032-a057-8af4f24cd187: 'Procédés théâtraux' # Procédés théâtraux
    cf856488-e716-4834-a558-395405d8eeee: Transcripteur # Transcripteur
    cfaaf21a-8fd0-4ce6-adcc-eba9f6c787a8: 'Autre(s) titre(s)' # Autre(s) titre(s)
    cfc8c93d-134d-4d7f-84dd-31c7c229e699: 'Date d’écriture (max)' # Date d’écriture (max)
    db53251e-e713-455c-a15e-37016be4971f: Accueil # Accueil
    dd4fcf15-6584-4f37-8317-ecaada78e196: Extrait # Extrait
    e0954bb8-d8bb-4fbb-b5e7-944b482e521e: Personnes # Personnes
    e2d5c38e-3607-4630-bddf-0875190aa133: 'Œuvres corrélées' # Œuvres corrélées
    e4e23bc0-a6bd-4075-943f-4607a5fac9be: 'Œuvres corrélées' # Œuvres corrélées
    e9d4c568-7f9b-4fe4-bb99-e3b7b2759c40: 'Lieu de la première représentation' # Lieu de la première représentation
    e170dd2d-c858-4261-834a-9c2fee02cbd5: Mots-clés # Mots-clés
    e205ebe8-5557-4b7c-a43f-9cf548e90c8d: Pays # Pays
    e9587719-a8d4-42d6-97c2-f0259ec67922: 'Institutions de conservation' # Institutions de conservation
    ea500c41-2beb-4ed4-a12c-afca214004c7: Superviseur # Superviseur
    ec7faa37-6b19-44d2-95ec-2b752648c37d: Langues # Langues
    ef2dfdac-243c-4f75-8385-ee787d2e7765: Images # Images
    f03405c5-53d6-4a5b-820a-1a1880a63524: 'Identifiant IDREF' # Identifiant IDREF
    f0767615-2b56-4d09-87d2-7485cedf5fc1: Users # Users
    f1aeb04a-7fb6-4c3c-87a1-59320850b52e: Personnages # Personnages
    f6c0a973-aaab-4aee-bbdc-c5f7fe02069a: IDs # IDs
    f9d69522-b5ad-442c-873f-739859f6e7f7: 'Registre(s) littéraire(s)' # Registre(s) littéraire(s)
    f7587c45-1123-417a-9e51-c0a292fb22e8: 'Autre(s) version(s) du même nom' # Autre(s) version(s) du même nom
    fa0087ff-5695-4bdc-8bf4-9650ee08cde6: Notice # Notice
    fa8f9cfe-9074-40b9-b300-5a58cd4ff61c: Publics # Publics
    fbbb13b9-a645-436f-82a9-ad8e5767acda: Œuvres # Œuvres
    fd390cb8-325d-419c-a64a-95714d698f94: Rôle(s) # Rôle(s)
    ffcbd130-d01a-46e8-be41-572fa13bf2fb: Commons # Commons
plugins:
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  preparse-field:
    edition: standard
    enabled: true
    schemaVersion: 1.0.5
  reasons:
    edition: standard
    enabled: true
    schemaVersion: 2.1.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  tag-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  workflow:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_WORKFLOW_KEY
    schemaVersion: 2.1.5
    settings:
      editorNotesRequired: ''
      editorNotifications: '1'
      editorNotificationsOptions:
        - replyToReviewer
      editorUserGroup: c8c55cf1-a8a5-4356-b4eb-7984788d01b2 # Contributeurs
      enabledSections: '*'
      lockDraftSubmissions: '1'
      publisherNotesRequired: ''
      publisherNotifications: '1'
      publisherUserGroup: a5c71adc-184b-49c4-8e1a-d251540bf2b1 # Chercheurs
      reviewerApprovalNotifications: ''
      reviewerNotifications: '1'
      reviewerUserGroups: ''
      selectedPublishers: ''
system:
  edition: pro
  live: true
  name: puppetplays
  retryDuration: null
  schemaVersion: 3.7.8
  timeZone: Europe/Paris
