dateModified: 1617289753
email:
  fromEmail: $EMAIL_SENDER
  fromName: Puppetplays
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: ''
    host: $EMAIL_HOSTNAME
    password: ''
    port: $EMAIL_PORT
    timeout: '10'
    useAuthentication: ''
    username: ''
  transportType: craft\mail\transportadapters\Smtp
plugins:
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  reasons:
    edition: standard
    enabled: true
    schemaVersion: 2.1.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: puppetplays
  retryDuration: null
  schemaVersion: 3.5.13
  timeZone: Europe/Paris
