dateModified: 1625756387
email:
  fromEmail: $EMAIL_SENDER
  fromName: Puppetplays
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: ''
    host: $EMAIL_HOSTNAME
    password: ''
    port: $EMAIL_PORT
    timeout: '10'
    useAuthentication: ''
    username: ''
  transportType: craft\mail\transportadapters\Smtp
plugins:
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  reasons:
    edition: standard
    enabled: true
    schemaVersion: 2.1.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  tag-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  workflow:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_WORKFLOW_KEY
    schemaVersion: 2.1.5
    settings:
      editorNotesRequired: ''
      editorNotifications: '1'
      editorNotificationsOptions: ''
      editorUserGroup: c8c55cf1-a8a5-4356-b4eb-7984788d01b2 # Contributeurs
      enabledSections: '*'
      lockDraftSubmissions: '1'
      publisherNotesRequired: ''
      publisherNotifications: '1'
      publisherUserGroup: a5c71adc-184b-49c4-8e1a-d251540bf2b1 # Chercheurs
      reviewerApprovalNotifications: ''
      reviewerNotifications: '1'
      reviewerUserGroups: ''
      selectedPublishers: '*'
system:
  edition: pro
  live: true
  name: puppetplays
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: Europe/Paris
