dateModified: 1616016510
email:
  fromEmail: no-reply@puppetplays.fr
  fromName: Puppetplays
  replyToEmail: null
  template: ''
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  reasons:
    edition: standard
    enabled: true
    schemaVersion: 2.1.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: puppetplays
  retryDuration: null
  schemaVersion: 3.5.13
  timeZone: Europe/Paris
